### PR TITLE
Add context argument to grammar recognizers (pull request)

### PR DESCRIPTION
**Pull request by jwcraftsman**
This pull request is a result of the discussion in #50.

The changes in this branch allow parsers to be extended by storing some extra state information in the context object that is manipulated by custom actions and examined by custom recognizers.  In order to achieve this, parglare was modified to allow recognizers to accept a context object as an optional first argument.  The change is backward-compatible with existing recognizers.  Python's introspection features are used to examine the recognizer's signature in order to determine the number of arguments to pass to the recognizer.

An attempt was made to make this work for GLR parsers by cloning the context object's "extra" attribute that is set aside for storing the extra parsing state.  Having user state stored in a special context attribute should be more efficient than cloning the whole context object and also reduces the possibility of name collisions between the context attributes used by parglare and those added by the user.  I don't understand all of the GLR logic, so it's likely that I missed something in the cloning and restoring of the context object, but this code does work for the example I posted in #50.

### CODE REVIEW

**Comment by igordejanovic** [comment]
Looks good. Merging. Thanks for your contribution.

I'm in the process of reworking parser to further improve on error reporting and I'll probably introduce some changes in the way context is handled. I'm thinking to do shallow copy of context as all its elements are immutable, while deep copying of `extra` attribute. This should make things easier, remove some boiler-plate code while not degrading performance I hope.

**Comment by igordejanovic** [comment]
This optional addition of context to recognizer would need some docs. So if you find some time to do it it would be greatly appreciated :)

**Comment by jwcraftsman** [comment]
It's great to see this merged in!  Thanks for being open to my suggestions.  I'll try to take a look at the documentation before too long.

**Comment by jwcraftsman** [comment]
It looks like there is a bunch of work going on in the error-reporting-rework branch.  Is it okay if I make a couple of documentation changes based on the master branch, or should I wait until things settle down?  I don't have time to write a lot of documentation, but I can add a description of the "extra" attribute and copy/deepcopy behavior in the Context object description of the Actions section and mention the optional context argument in the Recognizers section if that would be helpful.

**Comment by igordejanovic** [comment]
Hi Jeff. Yeah, there is a lot of changes going on at the moment so maybe it's better to wait some time for it to settle down.

**Comment by jwcraftsman** [comment]
No problem.  I thought that might be a good idea.

**Pull request merged**
