### PR TITLE
Use ordinary dicts for parse table serialization

### PR DESCRIPTION
**Pull request by SupraSummus**
Why I think this is a change for better:
* There is no need in using `OrderedDict` for table serialization. We don;t need information about order to reconstruct the tables.
* Use of OrderedDict may be misleading as it indicates that order matters. For example one may think that JSON is not suitable for serialization, because it doesn't preserve order of dict entries.
* Using regular dicts makes things easier when it comes to dumping and loading from `repr` (and possibly other representations / other processing).

### CODE REVIEW

**Comment by SupraSummus** [comment]
If `.pgt` files should be deterministic then I propose adding `sort_keys=True` to JSON dumping. Let me know if this is desired and I may add this change to the PR.

**Comment by igordejanovic** [comment]
Agreed. No need for `OrderedDict`.
And, yes, I think it would be better to have `pgt` json files deterministic as it would make life easier when working with version control or making tests based on comparing outputs.

**Comment by SupraSummus** [comment]
Updated.

**Comment by igordejanovic** [comment]
Looks good. Thanks.

**Pull request merged**
