### PR TITLE
Test for #72

### PR DESCRIPTION
**Pull request by SupraSummus**

### CODE REVIEW

**Comment by igordejanovic** [comment]
@SupraSummus Are those two test branches not valid anymore?

**Comment by SupraSummus** [comment]
I think they are. Will rebase, check them today's evening and let you know. Cheers.

**Comment by SupraSummus** [comment]
Ok, I've deleted the branches mistakenly - was cleaning the repo and clicked that trash can without thinking much. Now I restored the branches, but can't reopen the PRs. Are you able to do this @igordejanovic? If not I'll open new PRs, just let me know.

**Comment by igordejanovic** [comment]
@SupraSummus Nope. I don't have an option to reopen them. Please create new ones. Thanks.

**Pull request closed without merging**
