### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
@igordejanovic

**Comment by igordejanovic** [comment]
@KOLANICH Thanks for the contribution. [The tests are failing](https://travis-ci.org/igordejanovic/parglare/builds/643006755?utm_source=github_status&utm_medium=notification) for some Python versions. I'll investigate in the next days. Do you know why?

**Comment by KOLANICH** [comment]
Fixed.

**Comment by igordejanovic** [comment]
@KOLANICH Thanks. LGTM. `setuptools_scm` seems to be a nice solution for auto versioning.

**Pull request merged**
